THLY" }, label = { Text("Bulanan") }) }; NumberField(salary, { salary = it }, "Gaji pokok", Modifier.fillMaxWidth()); NumberField(meal, { meal = it }, "Uang makan / hari", Modifier.fillMaxWidth()); NumberField(otMeal, { otMeal = it }, "Makan lembur / hari", Modifier.fillMaxWidth()); NumberField(otRate, { otRate = it }, "Tarif lembur / jam", Modifier.fillMaxWidth()) } }, confirmButton = { Button(onClick = { if (name.isNotBlank()) save(Employee(name = name, position = position, salaryType = type, baseSalary = salary.toLongOrNull() ?: 0, mealDaily = meal.toLongOrNull() ?: 0, mealOvertime = otMeal.toLongOrNull() ?: 0, overtimeRate = otRate.toLongOrNull() ?: 0, standardWorkDays = if (type == "MONTHLY") 26 else 6)) }, colors = ButtonDefaults.buttonColors(containerColor = Charcoal)) { Text("Simpan") } }, dismissButton = { TextButton(onClick = close) { Text("Batal") } })
}

@Composable private fun CompanyDialog(initial: CompanyProfile, close: () -> Unit, save: (CompanyProfile) -> Unit) {
    var name by remember { mutableStateOf(initial.name) }; var address by remember { mutableStateOf(initial.address) }; var contact by remember { mutableStateOf(initial.contact) }
    var logo by remember { mutableStateOf(initial.logoUri) }; var signature by remember { mutableStateOf(initial.signatureUri) }; var stamp by remember { mutableStateOf(initial.stampUri) }
    var target by remember { mutableStateOf("") }
    val picker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri -> if (uri != null) when (target) { "logo" -> logo = uri.toString(); "signature" -> signature = uri.toString(); "stamp" -> stamp = uri.toString() } }
    AlertDialog(onDismissRequest = close, title = { Text("Data Perusahaan") }, text = { Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        OutlinedTextField(name, { name = it }, label = { Text("Nama perusahaan") }); OutlinedTextField(address, { address = it }, label = { Text("Alamat") }); OutlinedTextField(contact, { contact = it }, label = { Text("Kontak") })
        Text("Asset dokumen", fontWeight = FontWeight.Bold);
        Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) { Button(onClick = { target = "logo"; picker.launch("image/*") }, colors = ButtonDefaults.buttonColors(containerColor = Yellow), contentColor = Charcoal) { Text(if (logo == null) "Logo" else "✓ Logo") }; Button(onClick = { target = "signature"; picker.launch("image/*") }, colors = ButtonDefaults.buttonColors(containerColor = Yellow), contentColor = Charcoal) { Text(if (signature == null) "Tanda tangan" else "✓ TTD") }; Button(onClick = { target = "stamp"; picker.launch("image/*") }, colors = ButtonDefaults.buttonColors(containerColor = Yellow), contentColor = Charcoal) { Text(if (stamp == null) "Cap" else "✓ Cap") } }
    } }, confirmButton = { Button(onClick = { save(initial.copy(name = name, address = address, contact = contact, logoUri = logo, signatureUri = signature, stampUri = stamp)) }, colors = ButtonDefaults.buttonColors(containerColor = Charcoal)) { Text("Simpan") } }, dismissButton = { TextButton(onClick = close) { Text("Batal") } })
}

@Composable private fun LoanDialog(employees: List<Employee>, close: () -> Unit, save: (Loan) -> Unit) {
    var selected by remember { mutableStateOf<Employee?>(null) }; var amount by remember { mutableStateOf("") }; var desc by remember { mutableStateOf("") }
    AlertDialog(onDismissRequest = close, title = { Text("Tambah Kasbon") }, text = { Column(verticalArrangement = Arrangement.spacedBy(8.dp)) { EmployeeDropdown(employees, selected) { selected = it }; NumberField(amount, { amount = it }, "Nominal kasbon", Modifier.fillMaxWidth()); OutlinedTextField(desc, { desc = it }, label = { Text("Keterangan") }, modifier = Modifier.fillMaxWidth()); Text("Kasbon akan masuk sebagai potongan payroll pada periode yang sama dengan tanggal pencatatan.", fontSize = 11.sp, color = Color.Gray) } }, confirmButton = { Button(onClick = { selected?.let { save(Loan(employeeId = it.id, date = fmt(LocalDate.now()), amount = amount.toLongOrNull() ?: 0, description = desc)) } }, enabled = selected != null && (amount.toLongOrNull() ?: 0) > 0, colors = ButtonDefaults.buttonColors(containerColor = Charcoal)) { Text("Simpan") } }, dismissButton = { TextButton(onClick = close) { Text("Batal") } })
}

private fun shareSlip(context: Context, row: PayrollRow) {
    val pdf = PdfDocument(); val page = pdf.startPage(PdfDocument.PageInfo.Builder(595, 842, 1).create()); val canvas = page.canvas; val p = Paint().apply { color = android.graphics.Color.BLACK; textSize = 16f }
    var y = 55f; canvas.drawText("SLIP GAJI", 45f, y, p); y += 28; p.textSize = 13f; canvas.drawText(row.employee.name, 45f, y, p); y += 20; canvas.drawText(row.employee.position, 45f, y, p); y += 30
    listOf("Hari kerja: ${row.days}", "Gaji pokok: ${rupiah(row.base)}", "Uang makan: ${rupiah(row.meal)}", "Lembur: ${row.overtime} jam / ${rupiah(row.overtimePay)}", "Makan lembur: ${rupiah(row.overtimeMeal)}"