(date), present, late.toIntOrNull() ?: 0, overtime.toDoubleOrNull() ?: 0.0)) } } }, enabled = selected != null, modifier = Modifier.fillMaxWidth(), colors = ButtonDefaults.buttonColors(containerColor = Charcoal)) { Text("Simpan Absensi") }
        Spacer(Modifier.height(18.dp)); Text("Catatan: keterlambatan dicatat sebagai menit dan belum otomatis menjadi potongan sampai aturan potongan dikonfigurasi.", color = Color.Gray, fontSize = 12.sp)
    }
}

@Composable private fun EmployeeDropdown(employees: List<Employee>, selected: Employee?, onSelect: (Employee) -> Unit) {
    var expanded by remember { mutableStateOf(false) }
    Box { OutlinedButton(onClick = { expanded = true }, modifier = Modifier.fillMaxWidth()) { Text(selected?.name ?: "Pilih karyawan", modifier = Modifier.weight(1f)); Icon(Icons.Default.ExpandMore, null) }; DropdownMenu(expanded, { expanded = false }) { employees.forEach { e -> DropdownMenuItem(text = { Text(e.name) }, onClick = { onSelect(e); expanded = false }) } } }
}

@Composable private fun PayrollScreen(employees: List<Employee>, dao: PayrollDao) {
    var type by remember { mutableStateOf("MINGGUAN") }
    var results by remember { mutableStateOf<List<PayrollRow>>(emptyList()) }
    var generated by remember { mutableStateOf(false) }
    var reportMode by remember { mutableStateOf(false) }
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    Column(Modifier.fillMaxSize().padding(20.dp)) {
        Text("Payroll", fontSize = 28.sp, fontWeight = FontWeight.Bold); Text("Generate, review dan bagikan slip", color = Color.Gray); Spacer(Modifier.height(14.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { FilterChip(!reportMode, { reportMode = false }, label = { Text("Generate") }); FilterChip(reportMode, { reportMode = true }, label = { Text("Laporan Gaji") }) }
        Spacer(Modifier.height(10.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { FilterChip(type == "MINGGUAN", { type = "MINGGUAN" }, label = { Text("Mingguan") }); FilterChip(type == "BULANAN", { type = "BULANAN" }, label = { Text("Bulanan") }) }
        Spacer(Modifier.height(10.dp))
        Text(if (type == "MINGGUAN") "Periode: ${fmt(weekStart())} — ${fmt(weekEnd())}" else "Periode: ${fmt(monthStart())} — ${fmt(monthEnd())}", fontWeight = FontWeight.SemiBold)
        Spacer(Modifier.height(10.dp))
        Button(onClick = { scope.launch { results = calculatePayroll(employees, dao, type); generated = true } }, modifier = Modifier.fillMaxWidth(), colors = ButtonDefaults.buttonColors(containerColor = Charcoal)) { Icon(Icons.Default.Calculate, null); Spacer(Modifier.width(8.dp)); Text("Generate Payroll") }
        if (!reportMode && generated) {
            Spacer(Modifier.height(14.dp)); Text("Hasil Payroll", fontWeight = FontWeight.Bold, fontSize = 18.sp)
            LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp), modifier = Modifier.weight(1f)) { items(results) { row -> PayrollCard(row) { shareSlip(context, row) } } }
        }
        if (reportMode) {
            Spacer(Modifier.height(10.dp))
            Button(onClick = { scope.launch { results = calculatePayroll(employees, dao, type); generated = true } }, modifier = Modifier.fillMaxWidth(), colors = ButtonDefaults.buttonColors(containerColor = Charcoal)) { Text("Refresh Laporan") }
            if (generated) {
                val gross = results.sumOf { it.base + it.meal + it.overtimePay + it.overtimeMeal }
                val deductions = results.sumOf { it.loan }
                val net = results.sumOf { it.total }
                Spacer(Modifier.height(12.dp))
                ReportMetric("Total Gaji Pokok", rupiah(results.sumOf { it.base }))
                ReportMetric("Total Pendapatan", rupiah(gross))
                ReportMetric("Total Kasbon", rupiah(deductions))
                ReportMetric("Total Dibayarkan", rupiah(net))
                Spacer(Modifier.height(8.dp)); Text("Rincian per karyawan", fontWeight = FontWeight.Bold)
                LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.weight(1f)) { items(results) { r -> Row(Modifier.fillMaxWidth().background(Color.White, RoundedCornerShape(14.dp)).padding(14.dp)) { Text(r.employee.name, Modifier.weight(1f), fontWeight = FontWeight.SemiBold); Text(rupiah(r.total), fontWeight = FontWeight.Bold) } } }
            }
        }
    }
}

@Composable private fun ReportMetric(title: String, value: String) { Surface(shape = RoundedCornerShape(16.dp), color = Color.White, modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp)) { Row(Modifier.padding(16.dp), horizontalArrangement = Arrangement.SpaceBetween) { Text(title, color = Color.Gray); Text(value, fontWeight = FontWeight.Bold) } } }

data class PayrollRow(val employee: Employee, val days: Int, val lateMinutes: Int, val overtime: Double, val base: Long, val meal: Long, val overtimePay: Long, val overtimeMeal: Long, val loan: Long, val tot