from pathlib import Path
import re
p=Path('build-source/PayrollApp/app/src/main/java/com/gtkreative/payroll/MainActivity.kt')
s=p.read_text()
s=s.replace('private val Yellow = Color(0xFFFFC107)\nprivate val Charcoal = Color(0xFF202124)\nprivate val Soft = Color(0xFFF6F6F4)\nprivate val Green = Color(0xFF2E7D32)', 'private val Blue = Color(0xFF1268E8)\nprivate val Yellow = Color(0xFFFFC107)\nprivate val Charcoal = Color(0xFF172B4D)\nprivate val Soft = Color(0xFFF5F8FC)\nprivate val Green = Color(0xFF168A5B)')
s=s.replace('Text("Payroll", fontSize = 30.sp, fontWeight = FontWeight.Bold, color = Charcoal)\n        Text("Ringkasan penggajian", color = Color.Gray)', 'Text("Pe-Roll", fontSize = 30.sp, fontWeight = FontWeight.Bold, color = Charcoal)\n        Text("Absensi Hari Ini, Gaji Nanti", color = Color.Gray)')
attendance=r'''@Composable private fun AttendanceScreen(employees: List<Employee>, dao: PayrollDao) {
    var startText by remember { mutableStateOf(fmt(monthStart())) }
    var endText by remember { mutableStateOf(fmt(monthEnd())) }
    var days by remember { mutableStateOf<Map<Long, String>>(emptyMap()) }
    var late by remember { mutableStateOf<Map<Long, String>>(emptyMap()) }
    var overtime by remember { mutableStateOf<Map<Long, String>>(emptyMap()) }
    val scope = rememberCoroutineScope()
    val start = runCatching { LocalDate.parse(startText) }.getOrDefault(monthStart())
    val end = runCatching { LocalDate.parse(endText) }.getOrDefault(monthEnd())
    Column(Modifier.fillMaxSize().padding(20.dp)) {
        Text("Absensi", fontSize = 28.sp, fontWeight = FontWeight.Bold); Text("Total hari kerja per periode gaji", color = Color.Gray); Spacer(Modifier.height(14.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
            OutlinedTextField(startText, { startText = it }, label = { Text("Mulai periode") }, modifier = Modifier.weight(1f), singleLine = true)
            OutlinedTextField(endText, { endText = it }, label = { Text("Selesai periode") }, modifier = Modifier.weight(1f), singleLine = true)
        }
        Spacer(Modifier.height(8.dp)); Text("Masukkan total hari kerja tiap karyawan. Tidak perlu input satu per satu per tanggal.", color = Color.Gray, fontSize = 12.sp)
        Spacer(Modifier.height(10.dp)); LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp), modifier = Modifier.weight(1f)) {
            items(employees) { e ->
                Surface(shape = RoundedCornerShape(18.dp), color = Color.White, modifier = Modifier.fillMaxWidth()) { Column(Modifier.padding(14.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) { Column(Modifier.weight(1f)) { Text(e.name, fontWeight = FontWeight.Bold); Text(e.position, color = Color.Gray, fontSize = 12.sp) }; Text("${e.standardWorkDays} hari standar", color = Color.Gray, fontSize = 11.sp) }
                    Spacer(Modifier.height(8.dp)); Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
                        NumberField(days[e.id] ?: "", { days = days + (e.id to it) }, "Total hari kerja", Modifier.weight(1f))
                        NumberField(late[e.id] ?: "0", { late = late + (e.id to it) }, "Telat (menit)", Modifier.weight(1f))
                        NumberField(overtime[e.id] ?: "0", { overtime = overtime + (e.id to it) }, "Lembur (jam)", Modifier.weight(1f))
                    }
                } }
            }
        }
        Spacer(Modifier.height(10.dp)); Button(onClick = { scope.launch {
            employees.forEach { e ->
                val n=(days[e.id]?.toIntOrNull()?:0).coerceAtLeast(0); val l=late[e.id]?.toIntOrNull()?:0; val ot=overtime[e.id]?.toDoubleOrNull()?:0.0
                var d=start; var count=0
                while(!d.isAfter(end)&&count<n){ dao.upsertAttendance(Attendance(e.id,fmt(d),true,if(count==0)l else 0,if(count==0)ot else 0.0)); d=d.plusDays(1); count++ }
            }
        } }, modifier=Modifier.fillMaxWidth(), colors=ButtonDefaults.buttonColors(containerColor=Blue), enabled=employees.isNotEmpty()) { Text("Simpan Absensi Periode") }
    }
}

'''
s=re.sub(r'@Composable private fun AttendanceScreen.*?@Composable private fun EmployeeDropdown', attendance+'@Composable private fun EmployeeDropdown', s, flags=re.S)
payroll=r'''@Composable private fun PayrollScreen(employees: List<Employee>, dao: PayrollDao) {
    var type by remember { mutableStateOf("MINGGUAN") }
    var startText by remember { mutableStateOf(fmt(weekStart())) }
    var endText by remember { mutableStateOf(fmt(weekEnd())) }
    var results by remember { mutableStateOf<List<PayrollRow>>(emptyList()) }
    var generated by remember { mutableStateOf(false) }
    var preview by remember { mutableStateOf<PayrollRow?>(null) }
    val context = LocalContext.current; val scope = rememberCoroutineScope()
    Column(Modifier.fillMaxSize().padding(20.dp)) {
        Text("Payroll", fontSize=28.sp, fontWeight=FontWeight.Bold); Text("Slip gaji berdasarkan periode", color=Color.Gray); Spacer(Modifier.height(12.dp))
        Row(horizontalArrangement=Arrangement.spacedBy(8.dp)) { FilterChip(type=="MINGGUAN",{type="MINGGUAN";startText=fmt(weekStart());endText=fmt(weekEnd())},label={Text("Mingguan")}); FilterChip(type=="BULANAN",{type="BULANAN";startText=fmt(monthStart());endText=fmt(monthEnd())},label={Text("Bulanan")}) }
        Spacer(Modifier.height(8.dp)); Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()) { OutlinedTextField(startText,{startText=it},label={Text("Tanggal mulai slip")},modifier=Modifier.weight(1f),singleLine=true); OutlinedTextField(endText,{endText=it},label={Text("Tanggal selesai slip")},modifier=Modifier.weight(1f),singleLine=true) }
        Spacer(Modifier.height(10.dp)); Button(onClick={scope.launch{results=calculatePayroll(employees,dao,startText,endText);generated=true}},modifier=Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=Blue)){Text("Generate Payroll Periode")}
        if(generated){Spacer(Modifier.height(14.dp));Text("Slip Gaji",fontWeight=FontWeight.Bold,fontSize=18.sp);LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp),modifier=Modifier.weight(1f)){items(results){row->PayrollCard(row,{preview=row},{shareSlip(context,row,startText,endText)})}}}
    }
    if(preview!=null) SlipPreviewDialog(preview!!,startText,endText){preview=null}
}

'''
s=re.sub(r'@Composable private fun PayrollScreen.*?@Composable private fun ReportMetric', payroll+'@Composable private fun ReportMetric', s, flags=re.S)
s=s.replace('private suspend fun calculatePayroll(employees: List<Employee>, dao: PayrollDao, type: String): List<PayrollRow> {\n    val start = if (type == "MINGGUAN") weekStart() else monthStart(); val end = if (type == "MINGGUAN") weekEnd() else monthEnd();', 'private suspend fun calculatePayroll(employees: List<Employee>, dao: PayrollDao, startText: String, endText: String): List<PayrollRow> {\n    val start = runCatching { LocalDate.parse(startText) }.getOrDefault(monthStart()); val end = runCatching { LocalDate.parse(endText) }.getOrDefault(monthEnd());')
card=r'''@Composable private fun PayrollCard(row: PayrollRow, preview: () -> Unit, share: () -> Unit) {
    Surface(shape=RoundedCornerShape(18.dp),color=Color.White,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(row.employee.name,fontWeight=FontWeight.Bold,fontSize=17.sp);Text(row.employee.position,color=Color.Gray,fontSize=12.sp)};Text(rupiah(row.total),fontWeight=FontWeight.Bold,color=Green)};Spacer(Modifier.height(8.dp));Text("${row.days} hari kerja • ${row.overtime} jam lembur • ${row.lateMinutes} menit telat",fontSize=12.sp,color=Color.Gray);HorizontalDivider(Modifier.padding(vertical=10.dp));Text("Gaji pokok ${rupiah(row.base)}",fontSize=13.sp);Text("Makan ${rupiah(row.meal)} + lembur ${rupiah(row.overtimePay)} + makan lembur ${rupiah(row.overtimeMeal)}",fontSize=13.sp);Spacer(Modifier.height(8.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(onClick=preview){Text("Preview")};OutlinedButton(onClick=share){Text("Share")}}}}
}

@Composable private fun SlipPreviewDialog(row: PayrollRow,start:String,end:String,close:()->Unit){AlertDialog(onDismissRequest=close,title={Text("Preview Slip Gaji")},text={Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Pe-Roll",fontSize=20.sp,fontWeight=FontWeight.Bold,color=Blue);Text("Periode: $start — $end",color=Color.Gray);HorizontalDivider();Text(row.employee.name,fontWeight=FontWeight.Bold);Text(row.employee.position,color=Color.Gray);Text("Hari kerja: ${row.days}");Text("Gaji pokok: ${rupiah(row.base)}");Text("Uang makan: ${rupiah(row.meal)}");Text("Lembur: ${rupiah(row.overtimePay)}");Text("Makan lembur: ${rupiah(row.overtimeMeal)}");Text("Kasbon: -${rupiah(row.loan)}");HorizontalDivider();Text("TOTAL DITERIMA ${rupiah(row.total)}",fontWeight=FontWeight.Bold,fontSize=18.sp,color=Green)}},confirmButton={Button(onClick=close,colors=ButtonDefaults.buttonColors(containerColor=Blue)){Text("Tutup")}})}

'''
s=re.sub(r'@Composable private fun PayrollCard.*?@Composable private fun MoreScreen', card+'@Composable private fun MoreScreen', s, flags=re.S)
s=s.replace('var type by remember { mutableStateOf("WEEKLY") }', 'var type by remember { mutableStateOf("WEEKLY") }; var showPreview by remember { mutableStateOf(false) }')
s=s.replace('NumberField(otRate, { otRate = it }, "Tarif lembur / jam", Modifier.fillMaxWidth()) } }, confirmButton = {', 'NumberField(otRate, { otRate = it }, "Tarif lembur / jam", Modifier.fillMaxWidth()); OutlinedButton(onClick={showPreview=true},modifier=Modifier.fillMaxWidth(),enabled=(salary.toLongOrNull()?:0)>0){Icon(Icons.Default.Visibility,null);Spacer(Modifier.width(6.dp));Text("Preview Slip Gaji")} } }, confirmButton = {')
needle='\n}\n\n@Composable private fun CompanyDialog'
preview=r'''\n    if(showPreview){val e=Employee(name=name.ifBlank{"Nama Karyawan"},position=position.ifBlank{"Jabatan"},salaryType=type,baseSalary=salary.toLongOrNull()?:0,mealDaily=meal.toLongOrNull()?:0,mealOvertime=otMeal.toLongOrNull()?:0,overtimeRate=otRate.toLongOrNull()?:0,standardWorkDays=if(type=="MONTHLY")26 else 6);val d=e.standardWorkDays;val row=PayrollRow(e,d,0,0.0,e.baseSalary,e.mealDaily*d,0,0,0,e.baseSalary+e.mealDaily*d);SlipPreviewDialog(row,if(type=="WEEKLY")fmt(weekStart()) else fmt(monthStart()),if(type=="WEEKLY")fmt(weekEnd()) else fmt(monthEnd())){showPreview=false}}\n}\n\n@Composable private fun CompanyDialog'''
s=s.replace(needle,preview)
s=s.replace('canvas.drawText("SLIP GAJI", 45f, y, p)', 'canvas.drawText("PE-ROLL • SLIP GAJI", 45f, y, p)')
s=s.replace('private fun shareSlip(context: Context, row: PayrollRow)', 'private fun shareSlip(context: Context, row: PayrollRow, start: String, end: String)')
s=s.replace('y += 28; p.textSize = 13f;', 'y += 28; p.textSize = 13f; canvas.drawText("Periode: $start — $end", 45f, y, p); y += 20;')
p.write_text(s)
