from pathlib import Path
import re
p=Path("build-source/PayrollApp/app/src/main/java/com/gtkreative/payroll/MainActivity.kt")
s=p.read_text()
s=re.sub(r'private val Yellow = Color\(0xFFFFC107\).*?private val Red = Color\(0xFFC62828\)', '''private val Blue = Color(0xFF1268E8)
private val Yellow = Color(0xFFFFC107)
private val Charcoal = Color(0xFF172B4D)
private val Soft = Color(0xFFF5F8FC)
private val Green = Color(0xFF168A5B)
private val Red = Color(0xFFC62828)''',s,flags=re.S)

dash=r'''@Composable private fun Dashboard(employees: List<Employee>) {
Column(Modifier.fillMaxSize().padding(20.dp)){ Text("Pe-Roll",fontSize=30.sp,fontWeight=FontWeight.Bold,color=Charcoal); Text("Absensi Hari Ini, Gaji Nanti",color=Color.Gray); Spacer(Modifier.height(20.dp))
Surface(shape=RoundedCornerShape(24.dp),color=Charcoal,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(22.dp)){Text("PE-ROLL",color=Yellow,fontSize=12.sp,fontWeight=FontWeight.Bold);Text("Kelola karyawan, absensi dan payroll dalam satu aplikasi",color=Color.White,fontSize=20.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(10.dp));Text("${employees.size} Karyawan Aktif",color=Color.LightGray)}}
Spacer(Modifier.height(16.dp));Row(horizontalArrangement=Arrangement.spacedBy(12.dp),modifier=Modifier.fillMaxWidth()){StatCard("Karyawan",employees.size.toString(),Icons.Default.People,Modifier.weight(1f));StatCard("Sistem","Mingguan / Bulanan",Icons.Default.CalendarMonth,Modifier.weight(1f))}
Spacer(Modifier.height(16.dp));Surface(shape=RoundedCornerShape(20.dp),color=Color.White,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp)){Text("Alur kerja",fontWeight=FontWeight.Bold,fontSize=18.sp);listOf("1. Lengkapi data karyawan","2. Masukkan hari kerja, telat & lembur","3. Catat kasbon bila ada","4. Pilih tanggal gajian","5. Preview dan bagikan slip profesional").forEach{Text(it,Modifier.padding(vertical=5.dp),color=Color.DarkGray)}}}
}}
'''
s=re.sub(r'@Composable private fun Dashboard\(employees: List<Employee>\).*?@Composable private fun StatCard',dash+'@Composable private fun StatCard',s,flags=re.S)

emps=r'''@Composable private fun EmployeesScreen(employees: List<Employee>,dao: PayrollDao,add:()->Unit){
var selected by remember{mutableStateOf<Employee?>(null)}
Column(Modifier.fillMaxSize().padding(20.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Column{Text("Karyawan",fontSize=28.sp,fontWeight=FontWeight.Bold);Text("Data karyawan yang bisa diedit",color=Color.Gray)};FloatingActionButton(onClick=add,containerColor=Yellow,contentColor=Charcoal){Icon(Icons.Default.Add,null)}};Spacer(Modifier.height(16.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)){items(employees){e->EmployeeCard(e){selected=e}}}}
selected?.let{EmployeeDetailDialog(it,dao){selected=null}}
}
@Composable private fun EmployeeCard(e:Employee,onClick:()->Unit){
Surface(shape=RoundedCornerShape(18.dp),color=Color.White,modifier=Modifier.fillMaxWidth().clickable(onClick=onClick)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(14.dp),color=Yellow,modifier=Modifier.size(52.dp)){Box(contentAlignment=Alignment.Center){Text(e.name.take(1).uppercase(),fontWeight=FontWeight.Bold,fontSize=20.sp)}};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(e.name,fontWeight=FontWeight.Bold,fontSize=17.sp);Text(e.position,color=Color.Gray,fontSize=13.sp);Text("${if(e.salaryType=="WEEKLY")"Mingguan" else "Bulanan"} • ${rupiah(e.baseSalary)}",fontSize=12.sp);Text("Lembur ${rupiah(e.overtimeRate)}/jam",fontSize=12.sp,color=Blue)};Icon(Icons.Default.ChevronRight,null,tint=Color.Gray)}}
}
@Composable private fun EmployeeDetailDialog(e:Employee,dao:PayrollDao,close:()->Unit){
var name by remember(e.id){mutableStateOf(e.name)};var position by remember(e.id){mutableStateOf(e.position)};var salary by remember(e.id){mutableStateOf(e.baseSalary.toString())};var overtimeRate by remember(e.id){mutableStateOf(e.overtimeRate.toString())};var type by remember(e.id){mutableStateOf(e.salaryType)};var editing by remember(e.id){mutableStateOf(false)}
val loans by dao.loans(e.id).collectAsState(initial=emptyList());val scope=rememberCoroutineScope()
AlertDialog(onDismissRequest=close,title={Text("Detail Karyawan")},text={Column(verticalArrangement=Arrangement.spacedBy(9.dp)){
Text(if(editing)"Edit data karyawan" else e.name,fontSize=20.sp,fontWeight=FontWeight.Bold,color=Charcoal)
if(!editing){Text(e.position,color=Color.Gray);Text("Gaji pokok: ${rupiah(e.baseSalary)}");Text("Lembur: ${rupiah(e.overtimeRate)}/jam");Text("Sistem: ${if(e.salaryType=="WEEKLY")"Mingguan" else "Bulanan"}");HorizontalDivider();Text("Kasbon / Piutang",fontWeight=FontWeight.Bold);val totalLoan=loans.sumOf{it.amount};Text("Total kasbon tercatat: ${rupiah(totalLoan)}",color=if(totalLoan>0)Red else Green,fontWeight=FontWeight.SemiBold);if(loans.isEmpty())Text("Belum ada kasbon.",color=Color.Gray,fontSize=12.sp)else loans.take(5).forEach{loan->Text("${loan.date} • ${rupiah(loan.amount)}${if(loan.description.isBlank())"" else " • "+loan.description}",fontSize=12.sp,color=Color.DarkGray)}}else{
OutlinedTextField(name,{name=it},label={Text("Nama karyawan")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(position,{position=it},label={Text("Jabatan")},singleLine=true,modifier=Modifier.fillMaxWidth());NumberField(salary,{salary=it},"Gaji pokok",Modifier.fillMaxWidth());NumberField(overtimeRate,{overtimeRate=it},"Harga lemburan / jam",Modifier.fillMaxWidth());Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(type=="WEEKLY",{type="WEEKLY"},label={Text("Mingguan")});FilterChip(type=="MONTHLY",{type="MONTHLY"},label={Text("Bulanan")})}}
}},confirmButton={if(editing)Button(onClick={val updated=e.copy(name=name.trim(),position=position.trim(),baseSalary=salary.toLongOrNull()?:e.baseSalary,overtimeRate=overtimeRate.toLongOrNull()?:e.overtimeRate,salaryType=type);scope.launch{dao.updateEmployee(updated);close()}},enabled=name.isNotBlank()&&position.isNotBlank(),colors=ButtonDefaults.buttonColors(containerColor=Blue)){Text("Simpan Perubahan")}else Button(onClick={editing=true},colors=ButtonDefaults.buttonColors(containerColor=Blue)){Icon(Icons.Default.Edit,null);Spacer(Modifier.width(6.dp));Text("Edit")}},dismissButton={TextButton(onClick=close){Text(if(editing)"Batal" else "Tutup")}})
}
'''
s=re.sub(r'@Composable private fun EmployeesScreen.*?@Composable private fun AttendanceScreen',emps+'\n@Composable private fun AttendanceScreen',s,flags=re.S)

att=r'''@Composable private fun AttendanceScreen(employees:List<Employee>,dao:PayrollDao){
val scope=rememberCoroutineScope();val week=weekStart();var days by remember{mutableStateOf<Map<Long,String>>(emptyMap())};var late by remember{mutableStateOf<Map<Long,String>>(emptyMap())};var overtime by remember{mutableStateOf<Map<Long,String>>(emptyMap())}
Column(Modifier.fillMaxSize().padding(20.dp)){Text("Absensi",fontSize=28.sp,fontWeight=FontWeight.Bold);Text("Input mingguan per karyawan",color=Color.Gray);Spacer(Modifier.height(8.dp));Surface(shape=RoundedCornerShape(16.dp),color=Color.White,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text("Minggu ${fmt(week)} — ${fmt(weekEnd())}",fontWeight=FontWeight.SemiBold);Text("Isi total hari kerja, total menit telat, dan total jam lembur. Semua kolom bisa diedit.",color=Color.Gray,fontSize=12.sp)}};Spacer(Modifier.height(10.dp))
LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp),modifier=Modifier.weight(1f)){items(employees){e->Surface(shape=RoundedCornerShape(18.dp),color=Color.White,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(e.name,fontWeight=FontWeight.Bold);Text(e.position,color=Color.Gray,fontSize=12.sp)};Text("${e.standardWorkDays} hari standar",color=Color.Gray,fontSize=11.sp)};Spacer(Modifier.height(8.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()){NumberField(days[e.id]?: "",{days=days+(e.id to it)},"Hari kerja",Modifier.weight(1f));NumberField(late[e.id]?:"0",{late=late+(e.id to it)},"Telat (menit)",Modifier.weight(1f));NumberField(overtime[e.id]?:"0",{overtime=overtime+(e.id to it)},"Lembur (jam)",Modifier.weight(1f))}}}}}
Spacer(Modifier.height(10.dp));Button(onClick={scope.launch{dao.deleteAttendanceRange(fmt(week),fmt(weekEnd()));employees.forEach{e->val n=(days[e.id]?.toIntOrNull()?:0).coerceAtLeast(0);val l=(late[e.id]?.toIntOrNull()?:0).coerceAtLeast(0);val ot=(overtime[e.id]?.toDoubleOrNull()?:0.0).coerceAtLeast(0.0);var d=week;var count=0;while(!d.isAfter(weekEnd())&&count<n){if(d.dayOfWeek!=DayOfWeek.SUNDAY){dao.upsertAttendance(Attendance(e.id,fmt(d),true,if(count==0)l else 0,if(count==0)ot else 0.0));count++};d=d.plusDays(1)}}}},enabled=employees.isNotEmpty(),modifier=Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=Blue)){Text("Simpan Absensi Mingguan")}}
}
'''
s=re.sub(r'@Composable private fun AttendanceScreen.*?@Composable private fun EmployeeDropdown',att+'\n@Composable private fun EmployeeDropdown',s,flags=re.S)

datehelper=r'''@Composable private fun DatePickerField(label:String,date:LocalDate,onDateSelected:(LocalDate)->Unit,modifier:Modifier=Modifier){
var open by remember{mutableStateOf(false)}
OutlinedButton(onClick={open=true},modifier=modifier.height(56.dp),shape=RoundedCornerShape(8.dp)){Icon(Icons.Default.CalendarToday,null,tint=Blue);Spacer(Modifier.width(8.dp));Column(horizontalAlignment=Alignment.Start){Text(label,fontSize=11.sp,color=Color.Gray);Text(fmt(date),fontSize=15.sp,color=Charcoal)}}
if(open){val state=rememberDatePickerState(initialSelectedDateMillis=date.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli());DatePickerDialog(onDismissRequest={open=false},confirmButton={TextButton(onClick={state.selectedDateMillis?.let{onDateSelected(java.time.Instant.ofEpochMilli(it).atZone(java.time.ZoneId.systemDefault()).toLocalDate())};open=false}){Text("Pilih")}},dismissButton={TextButton(onClick={open=false}){Text("Batal")}}){DatePicker(state=state)}}
}
'''
s=s.replace('@Composable private fun PayrollScreen',datehelper+'@Composable private fun PayrollScreen',1)

pay=r'''@Composable private fun PayrollScreen(employees:List<Employee>,dao:PayrollDao){
var type by remember{mutableStateOf("WEEKLY")};var paymentDate by remember{mutableStateOf(LocalDate.now())};var results by remember{mutableStateOf<List<PayrollRow>>(emptyList())};var preview by remember{mutableStateOf<PayrollRow?>(null)};val company by dao.company().collectAsState(initial=null);val context=LocalContext.current;val scope=rememberCoroutineScope()
Column(Modifier.fillMaxSize().padding(20.dp)){Text("Payroll",fontSize=28.sp,fontWeight=FontWeight.Bold);Text("Tentukan tanggal gajian",color=Color.Gray);Spacer(Modifier.height(12.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(type=="WEEKLY",{type="WEEKLY"},label={Text("Mingguan")});FilterChip(type=="MONTHLY",{type="MONTHLY"},label={Text("Bulanan")})};Spacer(Modifier.height(10.dp));DatePickerField("Tanggal gajian",paymentDate,{paymentDate=it},Modifier.fillMaxWidth());Spacer(Modifier.height(8.dp));Surface(shape=RoundedCornerShape(14.dp),color=Color.White,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text("Periode dihitung otomatis",fontWeight=FontWeight.SemiBold);val ps=if(type=="WEEKLY")weekStartFor(paymentDate)else monthStartFor(paymentDate);val pe=if(type=="WEEKLY")ps.plusDays(6)else monthEndFor(paymentDate);Text("${fmt(ps)} — ${fmt(pe)}",color=Color.Gray,fontSize=13.sp)}};Spacer(Modifier.height(10.dp));Button(onClick={scope.launch{results=calculatePayroll(employees,dao,paymentDate,type)}},modifier=Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=Blue)){Icon(Icons.Default.Calculate,null);Spacer(Modifier.width(6.dp));Text("Generate Slip Gaji")};Spacer(Modifier.height(14.dp))
if(results.isNotEmpty()){Text("Slip Gaji",fontWeight=FontWeight.Bold,fontSize=20.sp);Spacer(Modifier.height(8.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp),modifier=Modifier.weight(1f)){items(results){row->PayrollCard(row,paymentDate,{preview=row},{shareSlip(context,company,row,paymentDate,type)})}}}else{Surface(shape=RoundedCornerShape(20.dp),color=Color.White,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.ReceiptLong,null,tint=Blue,modifier=Modifier.size(42.dp));Spacer(Modifier.height(8.dp));Text("Belum ada slip",fontWeight=FontWeight.Bold);Text("Pilih tanggal gajian lalu generate payroll.",color=Color.Gray,fontSize=13.sp)}}}}
preview?.let{SlipPreviewDialog(company,it,paymentDate){preview=null}}
}
'''
s=re.sub(r'@Composable private fun PayrollScreen.*?@Composable private fun ReportMetric',pay+'@Composable private fun ReportMetric',s,flags=re.S)

s=s.replace('data class PayrollRow','private fun weekStartFor(date:LocalDate)=date.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY))\nprivate fun monthStartFor(date:LocalDate)=date.withDayOfMonth(1)\nprivate fun monthEndFor(date:LocalDate)=date.withDayOfMonth(date.lengthOfMonth())\n\ndata class PayrollRow',1)
calc=r'''private suspend fun calculatePayroll(employees:List<Employee>,dao:PayrollDao,paymentDate:LocalDate,type:String):List<PayrollRow>{
val start=if(type=="WEEKLY")weekStartFor(paymentDate)else monthStartFor(paymentDate);val end=if(type=="WEEKLY")start.plusDays(6)else monthEndFor(paymentDate);val atts=dao.attendanceRange(fmt(start),fmt(end));val loans=dao.loansRange(fmt(start),fmt(end));val byEmp=atts.groupBy{it.employeeId}
return employees.map{e->val a=byEmp[e.id].orEmpty();val days=a.count{it.present};val late=a.sumOf{it.lateMinutes};val ot=a.sumOf{it.overtimeHours};val otDays=a.count{it.overtimeHours>0};val base=(e.baseSalary.toDouble()*days/e.standardWorkDays.coerceAtLeast(1)).roundToLong();val meal=e.mealDaily*days;val otp=(ot*e.overtimeRate).roundToLong();val otm=e.mealOvertime*otDays;val loan=loans.filter{it.employeeId==e.id}.sumOf{it.amount};PayrollRow(e,days,late,ot,base,meal,otp,otm,loan,base+meal+otp+otm-loan)}
}
'''
s=re.sub(r'private suspend fun calculatePayroll\(.*?\n\}\n\n@Composable private fun PayrollCard',calc+'@Composable private fun PayrollCard',s,flags=re.S)

cards=r'''@Composable private fun PayrollCard(row:PayrollRow,paymentDate:LocalDate,preview:()->Unit,share:()->Unit){
Surface(shape=RoundedCornerShape(20.dp),color=Color.White,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(row.employee.name,fontWeight=FontWeight.Bold,fontSize=18.sp);Text(row.employee.position,color=Color.Gray,fontSize=12.sp)};Text(rupiah(row.total),fontWeight=FontWeight.Bold,fontSize=17.sp,color=Green)};Text("Gajian ${fmt(paymentDate)}",color=Blue,fontSize=12.sp);HorizontalDivider(Modifier.padding(vertical=10.dp));Text("Hari kerja ${row.days} • Lembur ${row.overtime} jam • Telat ${row.lateMinutes} menit",color=Color.Gray,fontSize=12.sp);Spacer(Modifier.height(10.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(onClick=preview,modifier=Modifier.weight(1f)){Icon(Icons.Default.Visibility,null);Spacer(Modifier.width(5.dp));Text("Preview")};Button(onClick=share,modifier=Modifier.weight(1f),colors=ButtonDefaults.buttonColors(containerColor=Blue)){Icon(Icons.Default.Share,null);Spacer(Modifier.width(5.dp));Text("Bagikan")}}}}
}
@Composable private fun SlipPreviewDialog(company:CompanyProfile?,row:PayrollRow,paymentDate:LocalDate,close:()->Unit){
androidx.compose.ui.window.Dialog(onDismissRequest=close){Surface(shape=RoundedCornerShape(24.dp),color=Color.White,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(22.dp).heightIn(max=620.dp)){Row(verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(12.dp),color=Blue,modifier=Modifier.size(46.dp)){Box(contentAlignment=Alignment.Center){Icon(Icons.Default.ReceiptLong,null,tint=Color.White)}};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(company?.name?:"Pe-Roll",fontWeight=FontWeight.Bold,fontSize=18.sp);Text("SLIP GAJI",color=Blue,fontSize=12.sp,fontWeight=FontWeight.Bold)};IconButton(onClick=close){Icon(Icons.Default.Close,null)}};HorizontalDivider(Modifier.padding(vertical=12.dp));Text(row.employee.name,fontWeight=FontWeight.Bold,fontSize=19.sp);Text(row.employee.position,color=Color.Gray);Text("Tanggal gajian: ${fmt(paymentDate)}",color=Blue,fontSize=12.sp);Spacer(Modifier.height(14.dp));Text("PENDAPATAN",fontWeight=FontWeight.Bold,color=Charcoal);SlipLine("Gaji pokok",rupiah(row.base));SlipLine("Uang makan",rupiah(row.meal));SlipLine("Lembur",rupiah(row.overtimePay));SlipLine("Makan lembur",rupiah(row.overtimeMeal));HorizontalDivider(Modifier.padding(vertical=8.dp));Text("POTONGAN",fontWeight=FontWeight.Bold,color=Charcoal);SlipLine("Kasbon / piutang","- ${rupiah(row.loan)}");Spacer(Modifier.height(10.dp));Surface(shape=RoundedCornerShape(16.dp),color=Soft,modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(16.dp),horizontalArrangement=Arrangement.SpaceBetween){Text("TOTAL DITERIMA",fontWeight=FontWeight.Bold);Text(rupiah(row.total),fontWeight=FontWeight.Bold,fontSize=19.sp,color=Green)}};Spacer(Modifier.height(8.dp));Text("Hari kerja ${row.days} • Telat ${row.lateMinutes} menit • Lembur ${row.overtime} jam",color=Color.Gray,fontSize=11.sp);Spacer(Modifier.height(10.dp));Button(onClick=close,modifier=Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=Blue)){Text("Tutup")}}}}
}
@Composable private fun SlipLine(label:String,value:String){Row(Modifier.fillMaxWidth().padding(vertical=4.dp),horizontalArrangement=Arrangement.SpaceBetween){Text(label,color=Color.DarkGray);Text(value,fontWeight=FontWeight.SemiBold)}}
'''
s=re.sub(r'@Composable private fun PayrollCard.*?@Composable private fun MoreScreen',cards+'@Composable private fun MoreScreen',s,flags=re.S)

add=r'''@Composable private fun AddEmployeeDialog(close:()->Unit,save:(Employee)->Unit){
var name by remember{mutableStateOf("")};var position by remember{mutableStateOf("")};var salary by remember{mutableStateOf("")};var overtimeRate by remember{mutableStateOf("")};var type by remember{mutableStateOf("WEEKLY")};var showPreview by remember{mutableStateOf(false)}
AlertDialog(onDismissRequest=close,title={Text("Tambah Karyawan")},text={Column(verticalArrangement=Arrangement.spacedBy(9.dp)){OutlinedTextField(name,{name=it},label={Text("Nama karyawan")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(position,{position=it},label={Text("Jabatan")},singleLine=true,modifier=Modifier.fillMaxWidth());NumberField(salary,{salary=it},"Gaji pokok",Modifier.fillMaxWidth());NumberField(overtimeRate,{overtimeRate=it},"Harga lemburan / jam",Modifier.fillMaxWidth());Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(type=="WEEKLY",{type="WEEKLY"},label={Text("Mingguan")});FilterChip(type=="MONTHLY",{type="MONTHLY"},label={Text("Bulanan")})};OutlinedButton(onClick={showPreview=true},enabled=(salary.toLongOrNull()?:0)>0,modifier=Modifier.fillMaxWidth()){Icon(Icons.Default.Visibility,null);Spacer(Modifier.width(6.dp));Text("Preview Slip Gaji")}}},confirmButton={Button(onClick={if(name.isNotBlank()&&position.isNotBlank())save(Employee(name=name.trim(),position=position.trim(),salaryType=type,baseSalary=salary.toLongOrNull()?:0,mealDaily=0,mealOvertime=0,overtimeRate=overtimeRate.toLongOrNull()?:0,standardWorkDays=if(type=="MONTHLY")26 else 6))},enabled=name.isNotBlank()&&position.isNotBlank()&&(salary.toLongOrNull()?:0)>0,colors=ButtonDefaults.buttonColors(containerColor=Blue)){Text("Simpan")}},dismissButton={TextButton(onClick=close){Text("Batal")}})
if(showPreview){androidx.compose.ui.window.Dialog(onDismissRequest={showPreview=false}){Surface(shape=RoundedCornerShape(24.dp),color=Color.White,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(22.dp)){Text("PREVIEW SLIP GAJI",color=Blue,fontWeight=FontWeight.Bold,fontSize=12.sp);Spacer(Modifier.height(6.dp));Text(if(name.isBlank())"Nama Karyawan"else name,fontSize=21.sp,fontWeight=FontWeight.Bold);Text(if(position.isBlank())"Jabatan"else position,color=Color.Gray);HorizontalDivider(Modifier.padding(vertical=12.dp));SlipLine("Sistem",if(type=="WEEKLY")"Mingguan"else"Bulanan");SlipLine("Gaji pokok",rupiah(salary.toLongOrNull()?:0));SlipLine("Lembur / jam",rupiah(overtimeRate.toLongOrNull()?:0));Spacer(Modifier.height(12.dp));Surface(shape=RoundedCornerShape(14.dp),color=Soft,modifier=Modifier.fillMaxWidth()){Text("Slip akan lengkap setelah absensi dan kasbon masuk.",Modifier.padding(14.dp),color=Color.Gray,fontSize=12.sp)};Spacer(Modifier.height(12.dp));Button(onClick={showPreview=false},modifier=Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=Blue)){Text("Kembali")}}}}}
}
'''
s=re.sub(r'@Composable private fun AddEmployeeDialog.*?@Composable private fun CompanyDialog',add+'@Composable private fun CompanyDialog',s,flags=re.S)

share=r'''private fun shareSlip(context:Context,company:CompanyProfile?,row:PayrollRow,paymentDate:LocalDate,type:String){
val pdf=PdfDocument();val page=pdf.startPage(PdfDocument.PageInfo.Builder(595,842,1).create());val canvas=page.canvas;val blue=android.graphics.Color.rgb(18,104,232);val dark=android.graphics.Color.rgb(23,43,77);val gray=android.graphics.Color.rgb(100,110,125);val green=android.graphics.Color.rgb(22,138,91);val light=android.graphics.Color.rgb(245,248,252);val paint=Paint(Paint.ANTI_ALIAS_FLAG)
paint.color=android.graphics.Color.WHITE;canvas.drawRoundRect(android.graphics.RectF(34f,34f,561f,808f),24f,24f,paint);paint.color=blue;canvas.drawRoundRect(android.graphics.RectF(34f,34f,561f,145f),24f,24f,paint);paint.color=android.graphics.Color.WHITE;paint.textSize=24f;paint.typeface=android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);canvas.drawText(company?.name?:"Pe-Roll",58f,78f,paint);paint.textSize=12f;paint.typeface=android.graphics.Typeface.DEFAULT;canvas.drawText("SLIP GAJI",58f,101f,paint);canvas.drawText("Tanggal gajian: ${fmt(paymentDate)}",58f,122f,paint)
paint.color=dark;paint.textSize=20f;paint.typeface=android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);canvas.drawText(row.employee.name,58f,185f,paint);paint.color=gray;paint.textSize=13f;paint.typeface=android.graphics.Typeface.DEFAULT;canvas.drawText(row.employee.position,58f,207f,paint)
fun section(title:String,y:Float){paint.color=dark;paint.textSize=12f;paint.typeface=android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);canvas.drawText(title,58f,y,paint)}
fun line(label:String,value:String,y:Float){paint.color=gray;paint.textSize=13f;paint.typeface=android.graphics.Typeface.DEFAULT;canvas.drawText(label,58f,y,paint);paint.color=dark;paint.typeface=android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);canvas.drawText(value,410f,y,paint)}
section("PENDAPATAN",248f);line("Gaji pokok",rupiah(row.base),275f);line("Uang makan",rupiah(row.meal),299f);line("Lembur",rupiah(row.overtimePay),323f);line("Makan lembur",rupiah(row.overtimeMeal),347f);section("POTONGAN",393f);line("Kasbon / piutang","- "+rupiah(row.loan),423f);paint.color=light;canvas.drawRoundRect(android.graphics.RectF(50f,445f,545f,485f),12f,12f,paint);paint.color=blue;canvas.drawRoundRect(android.graphics.RectF(50f,505f,545f,580f),14f,14f,paint);paint.color=android.graphics.Color.WHITE;paint.textSize=12f;paint.typeface=android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);canvas.drawText("TOTAL DITERIMA",70f,535f,paint);paint.textSize=24f;canvas.drawText(rupiah(row.total),70f,565f,paint);paint.color=gray;paint.textSize=11f;paint.typeface=android.graphics.Typeface.DEFAULT;canvas.drawText("Hari kerja: ${row.days}   •   Telat: ${row.lateMinutes} menit   •   Lembur: ${row.overtime} jam",58f,625f,paint);canvas.drawText(company?.address?:"",58f,740f,paint);canvas.drawText(company?.contact?:"",58f,758f,paint);paint.color=green;paint.textSize=11f;paint.typeface=android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);canvas.drawText("Generated by Pe-Roll",58f,785f,paint)
pdf.finishPage(page);val dir=File(context.cacheDir,"slip").apply{mkdirs()};val safeName=row.employee.name.replace(Regex("[^A-Za-z0-9_-]"),"_");val file=File(dir,"Pe-Roll_${safeName}_${fmt(paymentDate)}.pdf");file.outputStream().use{pdf.writeTo(it)};pdf.close();val uri:Uri=FileProvider.getUriForFile(context,context.packageName+".fileprovider",file);val intent=android.content.Intent(android.content.Intent.ACTION_SEND).apply{type="application/pdf";putExtra(android.content.Intent.EXTRA_STREAM,uri);putExtra(android.content.Intent.EXTRA_SUBJECT,"Slip Gaji ${row.employee.name} - ${fmt(paymentDate)}");addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)};context.startActivity(android.content.Intent.createChooser(intent,"Bagikan slip gaji"))
}
'''
s=re.sub(r'private fun shareSlip\(.*?\n\}',share,s,count=1,flags=re.S)
s=s.replace('1 -> EmployeesScreen(employees, { showAdd = true })','1 -> EmployeesScreen(employees, dao, { showAdd = true })')
p.write_text(s)
